{
  "openapi": "3.0.3",
  "info": {
    "title": "Kroger API Reference",
    "description": "# Introduction\nPartner APIs enable official partners to access strategic functionality and data. Since the needs of our partners determine our Partner APIs, they are not open for public consumption.\n<br><br>\nAll Partner APIs provide access to the following Kroger subsidiaries:\n<ul>\n<li>Kroger</li>\n<li>Bakers</li>\n<li>City Market</li>\n<li>Dillons</li>\n<li>Food 4 Less</li>\n<li>Foods Co</li>\n<li>Fred Meyer</li>\n<li>Fry's</li>\n<li>Gerbes</li>\n<li>JayC</li>\n<li>King[...]",
    "termsOfService": "https://developer.kroger.com/terms",
    "contact": {
      "name": "API Support",
      "email": "APISupport@kroger.com"
    },
    "version": "1.2.1"
  },
  "servers": [
    {
      "url": "https://api.kroger.com/v1",
      "description": "Production Environment"
    },
    {
      "url": "https://api-ce.kroger.com/v1",
      "description": "Certification Environment"
    }
  ],
  "security": [
    {
      "CustomerContext": [
        "profile.name",
        "profile.basic",
        "profile.full",
        "profile.loyalty",
        "product.basic",
        "product.personalized",
        "cart.basic",
        "cart.basic:rw",
        "urn:com:kroger:partner:catalog:products:read",
        "urn:com:kroger:partner:unattended-pickup:order-events:write"
      ]
    },
    {
      "ClientContext": [
        "profile.exists",
        "product.basic",
        "delivery.basic",
        "delivery.basic:rw",
        "urn:com:kroger:partner:catalog:products:read",
        "urn:com:kroger:partner:order:checkout:write",
        "urn:com:kroger:partner:unattended-pickup:order-events:write"
      ]
    }
  ],
  "tags": [
    {
      "name": "Identity",
      "description": "The Identity API provides access to the profile information of an authenticated\nKroger customer. <br><br>The Identity API supports the following operations: <br>\n<table>\n<tr>\n  <th>Name</th>\n  <th>Method</th>\n  <th>Description</th>\n</tr>\n<tr>\n  <td>Profile information</td>\n  <td>GET</td>\n  <td>Returns a customer's full profile.</td>\n</tr>\n<tr>\n  <td>Profile query</td>\n  <td>GET</td>\n  <td>Determines if a customer's profile exist by email address.</td>\n</tr>[...]"
    },
    {
      "name": "Products",
      "description": "The Products API allows you to search the Kroger product catalog. \n\n### Pagination\n\nThe Product Search operation supports pagination with a default value of 10 results per page. Using the following parameters, you can extend and skip results in the response:\n\n`filter.limit` - Sets a limit on the number of products returned.<br>\n`filter.start` - Sets a number of results to skip in the response. \n\n**Note**: Since searching by a term acts as a fuzzy search, the order [...]"
    },
    {
      "name": "Locations",
      "description": "The Locations API provides access to all locations, chains, and departments \nthat are owned by The Kroger Co. <br><br>The Locations API \nsupports the following operations: <br>\n<table>\n<tr>\n  <th>Name</th>\n  <th>Method</th>\n  <th>Description</th>\n</tr>\n<tr>\n  <td>Location list</td>\n  <td>GET</td>\n  <td>Returns a list of locations matching a given criteria.</td>\n</tr>\n<tr>\n  <td>Location details</td>\n  <td>GET</td>\n  <td>Returns the details of a specific loc[...]"
    },
    {
      "name": "Carts",
      "description": "The Carts API provides access to create, view, and update a customer's cart. <br><br>\nThe Carts API supports the following operations: <br>\n<table>\n<tr>\n  <th>Name</th>\n  <th>Method</th>\n  <th>Description</th>\n</tr>\n<tr>\n  <td>User cart list</td>\n  <td>GET</td>\n  <td>Returns a list of carts for a specific customer.</td>\n</tr>\n<tr>\n  <td>Create a cart</td>\n  <td>POST</td>\n  <td>Creates a cart for a customer.</td>\n</tr>\n<tr>\n  <td>Cart by ID</td>\n  <td>GET[...]"
    },
    {
      "name": "Catalog",
      "description": "The Catalog API allows you to access Kroger's product catalog data. The catalog can be customized for clients based on their needs and requirements.<br><br>\nProduct search supports <code>pagination</code> with a default value of <code>20</code> results per page. \nUsing the following parameters in the request, you can configure the <code>size</code> and <code>offset</code> of the response:<br><br>\n  <li><code>page.size</code> - Sets a number of products to be listed in th[...]"
    },
    {
      "name": "Catalog V2",
      "description": "The Catalog V2 API allows you to access Kroger's catalog data. The catalog can be customized for clients based on their needs and requirements.<br><br>\n### <b>Pagination</b>\nProduct search supports <code>pagination</code> with a default value of <code>20</code> results per page. \nUsing the following parameters in the request, you can configure the <code>size</code> and <code>offset</code> of the response:<br><br>\n  <li><code>page.size</code> - Sets a number of products [...]"
    },
    {
      "name": "Deliveries",
      "description": "The Deliveries API provides access to both a list of deliveries and the \nability to update a delivery. <br><br>The Deliveries API \nsupports the following operations: <br>\n<table>\n<tr>\n  <th>Name</th>\n  <th>Method</th>\n  <th>Description</th>\n</tr>\n<tr>\n  <td>Get deliveries</td>\n  <td>GET</td>\n  <td>Returns a list of deliveries by actions.</td>\n</tr>\n<tr>\n  <td>Get non-deliveries</td>\n  <td>POST</td>\n  <td>Returns a list of outstanding deliveries.</td>\n</tr>[...]"
    },
    {
      "name": "OAuth2",
      "description": "## Client Credentials Grant\nWhen using the Client Credentials grant type, you can use your application's \nclient credentials as a form of authentication. If you are making a request to an API \nthat requires an OAuth2 scope, the scope must be included in the token request.\n\n## Authorization Code Grant\nTo authenticate a customer and act on their behalf, your application \nmust be able to perform both of the following steps of the Authorization Code grant.\n\n#### 1. Get[...]"
    },
    {
      "name": "Ship Order",
      "description": "The Ship Order API provides a way for a partner to submit a paid order for Kroger to ship in two steps:\n1. Get the amount of tax to charge on the order by using the POST endpoint with the `option.calculate` parameter.\n1. After the consumer has charged the customer (including the correct tax amount from step 1), create an order \nfor Kroger to ship by using the POST endpoint with no parameters.\n"
    },
    {
      "name": "Locker Pickup",
      "description": "The Locker Pickup API provides an interface for locker vendors to send status updates for unattended pickup orders to Kroger. This API supports the following operations:<br><br>The Lockers API \nsupports the following operations: <br>\n<table>\n<tr>\n  <th>Name</th>\n  <th>Method</th>\n  <th>Description</th>\n</tr>\n<tr>\n  <td>Update locker order</td>\n  <td>POST</td>\n  <td>Partners can pass the locker order status to Kroger.</td>\n</tr>\n</table>\n"
    }
  ],
  "paths": {
    "/partner/catalog/products": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "Catalog Search",
        "description": "Search the product catalog based upon specified criteria. Available parameters depend upon the type of location being searched and the modality. The two supported types of locations are as follows: <ul><li>Stores: Physical locations that customers are able to visit.</li><li>Distribution Centers: Locations that provide delivery services only with no customer access.</li></ul><br>The four supported modalities are as follows: <ul><li>DELIVERY: when items are delivered by a K[...]",
        "security": [
          {
            "CustomerContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          },
          {
            "ClientContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          }
        ]
      }
    },
    "/connect/oauth2/authorize": {
      "get": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Authorization Code",
        "description": "The redirect URL to authenticate a customer and receive an authorization code.",
        "operationId": "authorizationCode",
        "security": [
          {
            "CustomerContext": [
              "profile.name",
              "profile.basic",
              "profile.loyalty",
              "profile.full",
              "product.personalized",
              "cart.basic",
              "cart.basic:rw"
            ]
          }
        ]
      }
    },
    "/connect/oauth2/token": {
      "post": {
        "tags": [
          "OAuth2"
        ],
        "summary": "Access Token",
        "description": "The OAuth2 endpoint that provides access tokens.",
        "operationId": "accessToken",
        "security": [
          {
            "CustomerContext": [
              "profile.name",
              "profile.basic",
              "profile.full",
              "profile.loyalty",
              "product.basic",
              "product.personalized",
              "cart.basic",
              "cart.basic:rw"
            ]
          },
          {
            "ClientContext": [
              "profile.exists",
              "product.basic",
              "delivery.basic",
              "delivery.basic:rw"
            ]
          }
        ]
      }
    },
    "/identity/profile": {
      "get": {
        "tags": [
          "Identity"
        ],
        "summary": "Profile information",
        "description": "Provides access to an authenticated customer's profile information. \n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "profileGet",
        "security": [
          {
            "CustomerContext": [
              "profile.name",
              "profile.basic",
              "profile.full",
              "profile.loyalty"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Identity"
        ],
        "summary": "Profile query",
        "description": "Determine if a customer's profile exists by using their email address.",
        "operationId": "ProfileExists",
        "security": [
          {
            "ClientContext": [
              "profile.exists"
            ]
          }
        ]
      }
    },
    "/identity/profile/loyalty": {
      "get": {
        "tags": [
          "Identity"
        ],
        "summary": "Profile loyalty information",
        "description": "Provides access to an authenticated customer's loyalty information. \n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "profileLoyaltyGet",
        "security": [
          {
            "CustomerContext": [
              "profile.loyalty"
            ]
          }
        ]
      }
    },
    "/identity/profile/invoke/exists": {
      "get": {
        "tags": [
          "Identity"
        ],
        "summary": "Profile query",
        "description": "Determine if a customer's profile exists by using their \nemail address.\n",
        "operationId": "ProfileInvokeExists",
        "security": [
          {
            "ClientContext": [
              "profile.exists"
            ]
          }
        ]
      }
    },
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product search",
        "description": "Allows you to find products by passing in either a search term or product Id.\n\n### Initial Search Value Required\n\nAn initial search value is requred for all requests. You can use either of the following parameters as an initial search value: \n\n`filter.term` - When using the term parameter, the API performs a fuzzy search based on the term provided in the string. Search results are based on how relevant the term is to the product description.\n\n`filter.brand` - When[...]",
        "operationId": "productGet",
        "security": [
          {
            "CustomerContext": [
              "product.personalized",
              "product.basic"
            ]
          },
          {
            "ClientContext": [
              "product.basic"
            ]
          }
        ]
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Product details",
        "description": "Provides access to the details of a specific product by either using the `productId` or `UPC`. To return the product price, availability, and aisle location, you must include the `filter.locationId` query parameter.",
        "operationId": "productGetID",
        "security": [
          {
            "CustomerContext": [
              "product.personalized",
              "product.basic"
            ]
          },
          {
            "ClientContext": [
              "product.basic"
            ]
          }
        ]
      }
    },
    "/carts": {
      "get": {
        "tags": [
          "Carts"
        ],
        "summary": "User carts list",
        "description": "Provides access to return a list of all carts that belong to an authenticated customer.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "getCarts",
        "security": [
          {
            "CustomerContext": [
              "cart.basic"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Carts"
        ],
        "summary": "Create a cart",
        "description": "Provides access to create a new cart for an authenticated customer.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "createCart",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:rw"
            ]
          }
        ]
      }
    },
    "/carts/{id}": {
      "get": {
        "tags": [
          "Carts"
        ],
        "summary": "Cart by ID",
        "description": "Provides access to an authenticated customer's cart by ID.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "getCart",
        "security": [
          {
            "CustomerContext": [
              "cart.basic"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Carts"
        ],
        "summary": "Update cart",
        "description": "Provides access to update an authenticated customer's cart by ID. This operation only updates items that are already in a customer's cart.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "putCart",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:rw"
            ]
          }
        ]
      }
    },
    "/carts/{id}/items": {
      "post": {
        "tags": [
          "Carts"
        ],
        "summary": "Add to cart",
        "description": "Provides access to add items to an authenticated customer's cart.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "postCartItem",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:rw"
            ]
          }
        ]
      }
    },
    "/carts/{id}/items/{upc}": {
      "put": {
        "tags": [
          "Carts"
        ],
        "summary": "Updates item quantity",
        "description": "Provides access to update the quantity of an item in an authenticated customer's cart.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "putCartItem",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:rw"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Carts"
        ],
        "summary": "Delete item",
        "description": "Provides access to delete an item from an authenticated customer's cart.\n<br><br> **Note**: the customer must be authenticated using the OAuth2 Authorization \nCode grant type.\n",
        "operationId": "deleteCartItem",
        "security": [
          {
            "CustomerContext": [
              "cart.basic:rw"
            ]
          }
        ]
      }
    },
    "/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Location list",
        "description": "Provides access to a list of locations. If the parameter `filter.chain` is not provided, the results include all locations and chains owned by The Kroger Co.<br>You may include one of the following parameters to narrow search results within a geographic area:<br><br> <ul> <li> <code>filter.zipCode.near</code></li> <li> <code>filter.latLong.near</code></li> <li> <code>filter.lat.near</code> and <code>filter.lon.near</code></li> </ul>",
        "operationId": "SearchLocations",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Location details",
        "description": "Provides access to the details of a specific location by using the `locationId`.",
        "operationId": "LocationsGetByID",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Location query",
        "description": "Determines if a specific location exists by using the `locationId`.",
        "operationId": "LocationsExistsByID",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/chains": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain list",
        "description": "Provides access to a list of all chains owned by The Kroger Co.",
        "operationId": "ListChains",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/chains/{name}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain details",
        "description": "Provides access to the details of a specific chian by using the chain `name`.",
        "operationId": "GetChain",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Chain query",
        "description": "Determine if a specific chain exists by using the chain `name`.",
        "operationId": "ChainExists",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/departments": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Department list",
        "description": "Provides access to a list of all departments, including departments of chains owned by The Kroger Co.",
        "operationId": "ListDepartments",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/departments/{id}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "Department details",
        "description": "Provides access to the details of a specific department by using the `departmentId`. ",
        "operationId": "GetDepartment",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      },
      "head": {
        "tags": [
          "Locations"
        ],
        "summary": "Department query",
        "description": "Determine if a specific department exists by using the `departmentId`.",
        "operationId": "DepartmentExists",
        "security": [
          {
            "CustomerContext": [
              "N/A"
            ]
          },
          {
            "ClientContext": [
              "N/A"
            ]
          }
        ]
      }
    },
    "/courier/deliveries": {
      "get": {
        "tags": [
          "Deliveries"
        ],
        "summary": "Get deliveries",
        "description": "Provides access to a list of available deliveries for courier confirmation.  \nYou can use one of the optional `filter.followingAction` query parameter to filter deliveries:\n* `CONFIRM` -  For deliveries in pending confirmation.\n* `CONFIRM_EDITING` - For deliveries with pending edited that are not confirmed.\n* `CONFIRM_CANCELLATION` -  For deliveries in canceled by Kroger that are not confirmed.\n",
        "operationId": "getDeliveriesUsingGET",
        "security": [
          {
            "ClientContext": [
              "delivery.basic",
              "delivery.basic:rw"
            ]
          },
          {
            "CustomerContext": [
              "delivery.basic",
              "delivery.basic:rw"
            ]
          }
        ]
      }
    },
    "/courier/deliveries/non-delivered": {
      "get": {
        "tags": [
          "Deliveries"
        ],
        "summary": "Get non-delivered",
        "description": "Provides access to a list of outstanding deliveries. <br><br>Deliveries are considered\noutstanding when in the following states: \n* `PendingConfirmation` \n* `Scheduled` \n* `NotConfirmed`\n* `Edited`\n* `EditsNotConfirmed`\n* `EnRouteToPickup`\n* `AtPickup`\n* `PickedUp` \n* `EnRouteToDropoff`\n",
        "operationId": "getNonDeliveredByPartnerUsingGET",
        "security": [
          {
            "ClientContext": [
              "delivery.basic"
            ]
          },
          {
            "CustomerContext": [
              "delivery.basic"
            ]
          }
        ]
      }
    },
    "/courier/deliveries/{delivery_id}": {
      "post": {
        "tags": [
          "Deliveries"
        ],
        "summary": "Update delivery",
        "description": "Provides access to update a delivery status. The `action` parameter\nis required in the body for each update. <br><br>The payload parameter is only required\nwith the following actions:\n* `CONFIRM`\n* `CONFIRM_EDITING`\n* `CANCEL`\n* `EN_ROUTE_TO_PICK_UP`\n",
        "operationId": "updateUsingPOST",
        "security": [
          {
            "ClientContext": [
              "delivery.basic",
              "delivery.basic:rw"
            ]
          },
          {
            "CustomerContext": [
              "delivery.basic",
              "delivery.basic:rw"
            ]
          }
        ]
      }
    },
    "/partner/order/checkouts": {
      "post": {
        "tags": [
          "Ship Order"
        ],
        "summary": "Create ship order",
        "description": "This endpoint is used to support a two-step process for submitting a paid order to Kroger for shipping:\n1. Pass `option.calculate=summary` as a query parameter to get the appropriate tax for the order.\n2. After calculating the order cost (including the tax returned in step 1) and getting payment from the customer, \nsubmit the full order to Kroger with no query parameters.\n\nThe service does not currently validate the tax amount and total order payment in step 2, \nso [...]",
        "security": [
          {
            "CustomerContext": [
              "urn:com:kroger:partner:order:checkout:write"
            ]
          }
        ]
      }
    },
    "/partner/catalog/v2/products": {
      "get": {
        "tags": [
          "Catalog V2"
        ],
        "summary": "Catalog Search",
        "description": "Search the product catalog based upon specified criteria.",
        "security": [
          {
            "CustomerContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          },
          {
            "ClientContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          }
        ]
      }
    },
    "/partner/catalog/v2/products-inventory": {
      "get": {
        "tags": [
          "Catalog V2"
        ],
        "summary": "Catalog Inventory",
        "description": "Search a location's product catalog for inventory-specific details. Current stock levels, fulfillment status, and active promotions are included.",
        "security": [
          {
            "CustomerContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          },
          {
            "ClientContext": [
              "urn:com:kroger:partner:catalog:products:read"
            ]
          }
        ]
      }
    },
    "/lockers/v1/order-events": {
      "post": {
        "tags": [
          "Locker Pickup"
        ],
        "description": "The Locker Pickup API uses the following status values:<br><ul><li>LOADED - Status to indicate when the order has been loaded into the locker.</li><li>COLLECTED - Status to indicate when the order has been collected by the customer from the locker.</li></ul>",
        "security": [],
        "summary": "Update locker status"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "CustomerContext": {
        "type": "oauth2",
        "description": "When making an API request that is either returning personalized customer \ndata or acting on behalf of a customer, the customer's consent \nis required using the [Authorization Code Grant Type](#authorization-code-grant).\n",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.kroger.com/v1/connect/oauth2/authorize",
            "tokenUrl": "https://api.kroger.com/v1/connect/oauth2/token",
            "scopes": {
              "profile.name": "Grants read access to profile information. This scope returns only the ID, first name, and last name associated with the profile.",
              "profile.basic": "Grants read access to profile information. This scope returns only the email, name, address, and phone number associated with the profile.",
              "profile.loyalty": "Grants read access to profile loyalty information. This scope includes only the loyalty card number.",
              "profile.full": "Grants read access to profile information only. This scope includes profile.basic and profile.loyalty.",
              "product.personalized": "Grants read access to personalized product information.",
              "product.basic": "Grants read access to general product information.",
              "cart.basic": "Grants read access to the basic version of the cart.",
              "cart.basic:rw": "Grants read and write access to the basic version of the cart.",
              "urn:com:kroger:partner:catalog:products:read": "Grants read access to product catalog information.",
              "N/A": "No scope required."
            }
          }
        }
      },
      "ClientContext": {
        "type": "oauth2",
        "description": "When making API requests that do not require customer consent, you can use \nthe [Client Credentials Grant Type](#client-credentials-grant) to authenticate your OAuth2 \napplication.\n",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.kroger.com/v1/connect/oauth2/token",
            "scopes": {
              "profile.exists": "Grants read access to verify if a profile exists.",
              "product.basic": "Grants read access to general product information.",
              "delivery.basic": "Grants read access to courier delivery information.",
              "delivery.basic:rw": "Grants read and write access to courier delivery information.",
              "urn:com:kroger:partner:catalog:products:read": "Grants read access to product catalog information.",
              "urn:com:kroger:partner:order:checkout:write": "Allows partners to create new ship orders and view the created order details.",
              "urn:com:kroger:partner:unattended-pickup:order-events:write": "Grants write access to unattended locker order status.",
              "N/A": "No scope required."
            }
          }
        }
      }
    }
  },
  "x-tagGroups": [
    {
      "name": "Authorization Endpoints",
      "tags": [
        "OAuth2"
      ]
    },
    {
      "name": "API Reference",
      "tags": [
        "Identity",
        "Carts",
        "Catalog",
        "Catalog V2",
        "Products",
        "Locations",
        "Deliveries",
        "Ship Order",
        "Locker Pickup"
      ]
    }
  ]
}