version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@1.1.0
  slack: circleci/slack@3.4.2
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          name: build-prod
          filters:
            branches:
              only:
                - deploymeny-prep
          create-repo: true
          profile-name: myProfileName
          checkout: true
          repo: ingredient-cart-backend
          tag: "prod.$CIRCLE_WORKFLOW_ID"
          extra-build-args: "--build-arg mongo_db_url=$MONGO_DB_URL"
      - aws-ecs/deploy-service-update:
          context: aws
          name: prod-deploy
          filters:
            branches:
              only: deploymeny-prep
          requires:
            - build-prod
          family: "ingredient-cart-api-production"
          cluster-name: "prod-cluster"
          service-name: "ingredient-cart-production"
          container-image-name-updates: "container=ingredient-cart-prod,tag=prod.$CIRCLE_WORKFLOW_ID"
